import React, { useState, useEffect } from 'react';
import axios from 'axios';
import '../App.css';
import Recipe from '../components/Recipe';

const RecipeSearch = () => {
  // APP_ID and APP_KEY generated by API // needed for access
  const APP_ID = "b5cc8c91";
  const APP_KEY = "62798b351ed09c5dc984c106caf61a53";

  const [recipes, setRecipes] = useState([]);
  const [search, setSearch] = useState("");
  const [query, setQuery] = useState(search);

  // Fetch via axios, return data based on query and authenticate with APP_ID and APP_KEY
  const url = `https://api.edamam.com/search?q=${query}&app_id=${APP_ID}&app_key=${APP_KEY}`;


  // getRecipes whenever query is updated
  useEffect(() => {
    getRecipes();
  }, [query]);


  // Handles fetching recipes from API and returning response as JSON
  const getRecipes = () => {
    axios.get(url).then(response => {
      setRecipes(response.data.hits);
      // log hits for console visiblity, makes it easier to see accessible attributes of each item
      console.log(response.data.hits);
    })
  }
  
  // Update search state with user input
  const updateSearch = e => {
    setSearch(e.target.value);
  }

  // Set search to query so it is only updated once
  const getSearch = e => {
    e.preventDefault();
    setQuery(search);
  }

  return(
    <div className="recipe-search">
      <h1 className="page-header">Recipe Search</h1>
      <form onSubmit={getSearch} className="search-form">
        <input className="search-bar" type="text" value={search} onChange={updateSearch}/>
        <button className="search-button" type="submit">
          Search
        </button>
      </form>
      <div className="recipe">
        {recipes.map(recipe => (
          <Recipe key={recipe.recipe.label}
          title={recipe.recipe.label} 
          calories={Math.round(recipe.recipe.calories)}
          image={recipe.recipe.image} />
        ))}
      </div>
    </div>
  )
}

export default RecipeSearch;
